wandb_version: 1

batch_size:
  value: 8
dropout_c:
  value: 0.1
dropout_ga:
  value: 0.15
epochs:
  value: 50
learning_rate:
  value: 0.00025
num_features_c1:
  value: 8
num_features_c2:
  value: 16
num_features_c3:
  value: 32
