wandb_version: 1

batch_size:
  value: 4
dropout_c:
  value: 0.15
dropout_ga:
  value: 0.3
epochs:
  value: 10
learning_rate:
  value: 0.0001
num_features_c1:
  value: 8
num_features_c2:
  value: 32
num_features_c3:
  value: 8
