wandb_version: 1

batch_size:
  value: 14
dropout_c:
  value: 0.15
dropout_ga:
  value: 0.35
epochs:
  value: 30
learning_rate:
  value: 5.0e-05
num_features_c1:
  value: 4
num_features_c2:
  value: 16
num_features_c3:
  value: 8
