wandb_version: 1

batch_size:
  value: 32
dense:
  value: 16
dropout:
  value: 0.25
epochs:
  value: 25
learning_rate:
  value: 0.005
num_features_l1:
  value: 64
num_features_l2:
  value: 16
num_features_l3:
  value: 128
num_features_l4:
  value: 16
