wandb_version: 1

batch_size:
  value: 8
dense:
  value: 128
dropout:
  value: 0.35
epochs:
  value: 20
learning_rate:
  value: 0.001
num_features_l1:
  value: 16
num_features_l2:
  value: 128
num_features_l3:
  value: 128
num_features_l4:
  value: 128
