wandb_version: 1

batch_size:
  value: 8
dense:
  value: 16
dropout:
  value: 0.5
epochs:
  value: 25
learning_rate:
  value: 0.0005
num_features_l1:
  value: 128
num_features_l2:
  value: 128
num_features_l3:
  value: 64
num_features_l4:
  value: 32
