wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1657910780
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 16
      4: 3.9.12
      5: 0.12.17
      8:
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 4
dropout_c:
  desc: null
  value: 0.3
dropout_ga:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0003
num_features_c1:
  desc: null
  value: 64
num_features_c2:
  desc: null
  value: 64
num_features_c3:
  desc: null
  value: 128
num_features_c4:
  desc: null
  value: 64
