wandb_version: 1

batch_size:
  value: 4
dropout_c:
  value: 0.25
dropout_ga:
  value: 0.15
epochs:
  value: 10
learning_rate:
  value: 0.005
num_features_c1:
  value: 16
num_features_c2:
  value: 128
num_features_c3:
  value: 16
num_features_c4:
  value: 64
