wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655921671
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.17
      8:
      - 5
batch_size:
  desc: null
  value: 16
c_dropout:
  desc: null
  value: 0.2
ga_dropout:
  desc: null
  value: 0.2
l1:
  desc: null
  value: 0.0001
l2:
  desc: null
  value: 0.0001
learning_rate:
  desc: null
  value: 0.001
max_epochs:
  desc: null
  value: 50
min_epochs:
  desc: null
  value: 10
num_features_c1:
  desc: null
  value: 16
num_features_c2:
  desc: null
  value: 32
num_features_c3:
  desc: null
  value: 64
num_features_c4:
  desc: null
  value: 128
