wandb_version: 1

batch_size:
  value: 4
dropout_c:
  value: 0.1
dropout_ga:
  value: 0.3
epochs:
  value: 40
learning_rate:
  value: 1.0e-05
num_features_c1:
  value: 16
num_features_c2:
  value: 4
num_features_c3:
  value: 8
