wandb_version: 1

batch_size:
  value: 14
dropout_c:
  value: 0.25
dropout_ga:
  value: 0
epochs:
  value: 20
learning_rate:
  value: 5.0e-05
num_features_c1:
  value: 64
num_features_c2:
  value: 4
num_features_c3:
  value: 64
