wandb_version: 1

batch_size:
  value: 4
dropout_c:
  value: 0
dropout_ga:
  value: 0.2
epochs:
  value: 40
learning_rate:
  value: 0.00025
num_features_c1:
  value: 8
num_features_c2:
  value: 4
num_features_c3:
  value: 8
