wandb_version: 1

batch_size:
  value: 2
dropout_c:
  value: 0.4
dropout_ga:
  value: 0.3
epochs:
  value: 40
learning_rate:
  value: 5.0e-05
num_features_c1:
  value: 128
num_features_c2:
  value: 128
num_features_c3:
  value: 128
