wandb_version: 1

batch_size:
  value: 2
dropout_c:
  value: 0.15
dropout_ga:
  value: 0.2
epochs:
  value: 30
learning_rate:
  value: 0.001
num_features_c1:
  value: 128
num_features_c2:
  value: 128
num_features_c3:
  value: 128
