wandb_version: 1

batch_size:
  value: 16
dropout_c:
  value: 0
dropout_ga:
  value: 0.05
epochs:
  value: 40
learning_rate:
  value: 0.00025
num_features_c1:
  value: 16
num_features_c2:
  value: 4
num_features_c3:
  value: 8
