wandb_version: 1

batch_size:
  value: 128
dropout_c:
  value: 0.15
dropout_ga:
  value: 0.4
epochs:
  value: 80
learning_rate:
  value: 0.01
num_features_c1:
  value: 128
num_features_c2:
  value: 64
num_features_c3:
  value: 64
num_features_c4:
  value: 128
