wandb_version: 1

batch_size:
  value: 8
dropout_c:
  value: 0.35
dropout_ga:
  value: 0.25
epochs:
  value: 70
learning_rate:
  value: 0.0005
num_features_c1:
  value: 16
num_features_c2:
  value: 16
num_features_c3:
  value: 64
num_features_c4:
  value: 128
