wandb_version: 1

batch_size:
  value: 16
dropout_c:
  value: 0.2
dropout_ga:
  value: 0.25
epochs:
  value: 60
learning_rate:
  value: 0.0001
num_features_c1:
  value: 16
num_features_c2:
  value: 128
num_features_c3:
  value: 32
num_features_c4:
  value: 32
