wandb_version: 1

batch_size:
  value: 32
dropout_c:
  value: 0.35
dropout_ga:
  value: 0.4
epochs:
  value: 100
learning_rate:
  value: 0.0001
num_features_c1:
  value: 64
num_features_c2:
  value: 64
num_features_c3:
  value: 32
num_features_c4:
  value: 16
